"""Scoping of the oa-cohorts owned tables.

``orm_loader.helpers.Base`` is shared with ``omop_alchemy``: importing
``oa_cohorts.query`` registers the 15 oa-cohorts tables onto a metadata object
that already carries the ~39 OMOP CDM tables. Every schema operation in this
package must therefore work from an explicit owned-table set rather than from
``Base.metadata`` wholesale, or it would try to create (and later report drift
against) the entire CDM in the dashboard database.
"""

from __future__ import annotations

import importlib
from functools import lru_cache

import sqlalchemy as sa
from orm_loader.helpers import Base

#: Modules scanned for module-level ``sa.Table`` objects (association tables that
#: have no mapped class and so never appear in ``Base.registry.mappers``).
_TABLE_BEARING_MODULES: tuple[str, ...] = (
    "oa_cohorts.query.dash_cohort",
    "oa_cohorts.query.report",
    "oa_cohorts.query.subquery",
)

#: Only the query package defines the dashboard config schema. This is
#: deliberately narrower than "anything under oa_cohorts": the classes in
#: ``oa_cohorts.measurables`` are mapped onto the CDM materialized views owned
#: by omop_constructs (``condition_treatment_episode_mv`` and friends). They
#: live in the CDM database, are created by another package, and must never be
#: created, migrated or drift-checked from here.
_OWNED_PACKAGE_PREFIX = "oa_cohorts.query"


def load_query_metadata() -> None:
    """Import the query ORM modules so their tables register on ``Base.metadata``."""
    importlib.import_module("oa_cohorts.query")


@lru_cache(maxsize=1)
def owned_tables() -> tuple[sa.Table, ...]:
    """Return the tables oa-cohorts owns, in dependency-safe creation order.

    Discovery is by declaring module, not by a hardcoded name list, so a new
    model added under ``oa_cohorts.query`` is picked up without touching this
    file. Tables are returned in ``metadata.sorted_tables`` order so foreign
    keys resolve when they are created in sequence.
    """
    load_query_metadata()

    names: set[str] = set()

    for mapper in Base.registry.mappers:
        model = mapper.class_
        if not model.__module__.startswith(_OWNED_PACKAGE_PREFIX):
            continue
        table = model.__table__
        if isinstance(table, sa.Table) and table.metadata is Base.metadata:
            names.add(table.name)

    for module_name in _TABLE_BEARING_MODULES:
        module = importlib.import_module(module_name)
        for value in vars(module).values():
            if isinstance(value, sa.Table) and value.metadata is Base.metadata:
                names.add(value.name)

    # sort_tables over just the owned subset, not Base.metadata.sorted_tables.
    # The CDM half of the shared metadata has unresolvable FK cycles (concept,
    # person, visit_occurrence and friends), so sorting the whole thing emits a
    # SAWarning that says it "may raise an error in a future release". The 15
    # owned tables are acyclic on their own.
    return tuple(sa.schema.sort_tables([table for table in Base.metadata.tables.values()
                                        if table.name in names]))


@lru_cache(maxsize=1)
def owned_table_names() -> frozenset[str]:
    """Return the names of the tables oa-cohorts owns."""
    return frozenset(table.name for table in owned_tables())


@lru_cache(maxsize=1)
def owned_metadata() -> sa.MetaData:
    """A ``MetaData`` holding only the owned tables, for comparison.

    Alembic's ``compare_metadata`` sorts whatever metadata it is handed, so
    passing the shared ``Base.metadata`` drags the cyclic CDM tables through
    the sort and emits a SAWarning per call. Copying the owned tables into
    their own object avoids that.

    The naming convention is carried across deliberately: constraint names in a
    live database were generated by ``orm_loader``'s convention, and a metadata
    without it would compare every constraint as differently-named. There are
    no foreign keys from the owned tables into the CDM, so the copy is closed
    over its own contents.
    """
    scoped = sa.MetaData(naming_convention=Base.metadata.naming_convention)
    for table in owned_tables():
        table.to_metadata(scoped)
    return scoped


__all__ = [
    "load_query_metadata",
    "owned_metadata",
    "owned_table_names",
    "owned_tables",
]
