"""baseline: oa-cohorts dashboard schema as of 0.8.7

A frozen snapshot of the 15 oa-cohorts tables as they stood in **0.8.7**, the
oldest release whose databases are still in service. Existing databases adopt
it via ``oa-cohorts schema bootstrap``, which stamps a revision without running
any DDL; fresh databases get it applied for real and then continue through the
later revisions.

Deliberately not "the current models". 0.9.0 changed ``report.report_create_date``
and ``report_edit_date`` from ``sa.DateTime`` to ``sa.Date``, so a database
created by 0.8.7 or earlier has TIMESTAMP columns and matches *this* revision,
while a 0.9.0 database has DATE columns and matches ``0002``. A baseline
describing only the newer shape would leave every pre-0.9.0 database matching no
revision at all, and ``schema bootstrap`` would refuse to adopt it.

Do not edit this file to track model changes — add a new revision instead. The
snapshot must keep describing the schema this revision creates, including the
enum label sets, or ``schema check`` loses its reference point.

Revision ID: 0001_baseline
Revises:
Create Date: 2026-08-10

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from oa_cohorts.schema.enum_ops import sync_enum_labels

revision: str = '0001_baseline'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Frozen snapshot of the label sets this revision creates, matching the
# sa.Enum declarations below. Deliberately literal rather than read from
# oa_cohorts.core.enums: a revision must keep describing what it created,
# not follow the models as they move.
_ENUM_LABELS: dict[str, tuple[str, ...]] = {
    'resultdatesource': (
        'anchor', 'candidate', 'greatest', 'least',
    ),
    'rulecombination': (
        'rule_or', 'rule_and', 'rule_except',
    ),
    'rulematcher': (
        'substring', 'exact', 'hierarchy', 'absence', 'presence', 'hierarchyexclusion',
        'scalar', 'phenotype', 'predicate',
    ),
    'ruletarget': (
        'dx_any', 'dx_primary', 'dx_first_primary', 'dx_mets', 'dx_stage', 'tx_any',
        'tx_first_line', 'tx_current_episode', 'tx_chemotherapy', 'tx_radiotherapy',
        'tx_surgical', 'tx_concurrent', 'demog_gender', 'demog_death', 'obs_value',
        'obs_concept', 'proc_concept', 'meas_concept', 'meas_value_num', 'meas_value_concept',
        'tx_to_death_window', 'dx_to_tx_window', 'referral_to_tx_window',
        'referral_to_specialist_window', 'intent_rt', 'intent_sact', 'intent_concurrent_rt',
        'ev_visit',
    ),
    'ruletemporality': (
        'dt_any', 'dt_current_start', 'dt_stage', 'dt_mets', 'dt_treatment_start',
        'dt_treatment_end', 'dt_concurrent', 'dt_treat', 'dt_rad', 'dt_surg', 'dt_obs',
        'dt_proc_start', 'dt_meas', 'dt_consult', 'dt_death', 'dt_numerator', 'dt_denominator',
        'dt_visit',
    ),
    'thresholddirection': (
        'gt', 'lt', 'eq', 'neq',
    ),
    'windowpickstrategy': (
        'any', 'earliest', 'latest', 'closest',
    ),
}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dash_cohort',
    sa.Column('dash_cohort_id', sa.Integer(), nullable=False),
    sa.Column('dash_cohort_name', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('dash_cohort_id', name=op.f('pk_dash_cohort'))
    )
    op.create_table('phenotype',
    sa.Column('phenotype_id', sa.Integer(), nullable=False),
    sa.Column('phenotype_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('phenotype_id', name=op.f('pk_phenotype')),
    sa.UniqueConstraint('phenotype_name', name=op.f('uq_phenotype_phenotype_name'))
    )
    op.create_table('report',
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('report_name', sa.String(length=250), nullable=False),
    sa.Column('report_short_name', sa.String(length=50), nullable=False),
    sa.Column('report_description', sa.String(length=1000), nullable=False),
    # sa.DateTime, not sa.Date: this is the 0.8.7 shape. 0002 converts them.
    sa.Column('report_create_date', sa.DateTime(), nullable=False),
    sa.Column('report_edit_date', sa.DateTime(), nullable=False),
    sa.Column('report_author', sa.String(length=250), nullable=False),
    sa.Column('report_owner', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('report_id', name=op.f('pk_report')),
    sa.UniqueConstraint('report_short_name', name=op.f('uq_report_report_short_name'))
    )
    op.create_table('subquery',
    sa.Column('subquery_id', sa.Integer(), nullable=False),
    sa.Column('target', sa.Enum('dx_any', 'dx_primary', 'dx_first_primary', 'dx_mets', 'dx_stage', 'tx_any', 'tx_first_line', 'tx_current_episode', 'tx_chemotherapy', 'tx_radiotherapy', 'tx_surgical', 'tx_concurrent', 'demog_gender', 'demog_death', 'obs_value', 'obs_concept', 'proc_concept', 'meas_concept', 'meas_value_num', 'meas_value_concept', 'tx_to_death_window', 'dx_to_tx_window', 'referral_to_tx_window', 'referral_to_specialist_window', 'intent_rt', 'intent_sact', 'intent_concurrent_rt', 'ev_visit', name='ruletarget'), nullable=False),
    sa.Column('temporality', sa.Enum('dt_any', 'dt_current_start', 'dt_stage', 'dt_mets', 'dt_treatment_start', 'dt_treatment_end', 'dt_concurrent', 'dt_treat', 'dt_rad', 'dt_surg', 'dt_obs', 'dt_proc_start', 'dt_meas', 'dt_consult', 'dt_death', 'dt_numerator', 'dt_denominator', 'dt_visit', name='ruletemporality'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('short_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('subquery_id', name=op.f('pk_subquery'))
    )
    op.create_table('measure',
    sa.Column('measure_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('combination', sa.Enum('rule_or', 'rule_and', 'rule_except', name='rulecombination'), nullable=False),
    sa.Column('subquery_id', sa.Integer(), nullable=True),
    sa.Column('person_ep_override', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['subquery_id'], ['subquery.subquery_id'], name=op.f('fk_measure_subquery_id_subquery')),
    sa.PrimaryKeyConstraint('measure_id', name=op.f('pk_measure'))
    )
    op.create_table('phenotype_definition',
    sa.Column('phenotype_id', sa.Integer(), nullable=False),
    sa.Column('query_concept_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['phenotype_id'], ['phenotype.phenotype_id'], name=op.f('fk_phenotype_definition_phenotype_id_phenotype')),
    # No UniqueConstraint over (phenotype_id, query_concept_id): the primary key
    # below already enforces it. Postgres silently drops the duplicate but
    # SQLite creates it, which left the two backends disagreeing and produced a
    # permanent 'remove_constraint' in `schema check` on SQLite.
    sa.PrimaryKeyConstraint('phenotype_id', 'query_concept_id', name=op.f('pk_phenotype_definition'))
    )
    op.create_table('query_rule',
    sa.Column('query_rule_id', sa.Integer(), nullable=False),
    sa.Column('matcher', sa.Enum('substring', 'exact', 'hierarchy', 'absence', 'presence', 'hierarchyexclusion', 'scalar', 'phenotype', 'predicate', name='rulematcher'), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('scalar_threshold', sa.Integer(), nullable=True),
    sa.Column('threshold_direction', sa.Enum('gt', 'lt', 'eq', 'neq', name='thresholddirection'), nullable=True),
    sa.Column('threshold_comparator', sa.Enum('dx_any', 'dx_primary', 'dx_first_primary', 'dx_mets', 'dx_stage', 'tx_any', 'tx_first_line', 'tx_current_episode', 'tx_chemotherapy', 'tx_radiotherapy', 'tx_surgical', 'tx_concurrent', 'demog_gender', 'demog_death', 'obs_value', 'obs_concept', 'proc_concept', 'meas_concept', 'meas_value_num', 'meas_value_concept', 'tx_to_death_window', 'dx_to_tx_window', 'referral_to_tx_window', 'referral_to_specialist_window', 'intent_rt', 'intent_sact', 'intent_concurrent_rt', 'ev_visit', name='ruletarget'), nullable=True),
    sa.Column('phenotype_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['phenotype_id'], ['phenotype.phenotype_id'], name=op.f('fk_query_rule_phenotype_id_phenotype')),
    sa.PrimaryKeyConstraint('query_rule_id', name=op.f('pk_query_rule'))
    )
    with op.batch_alter_table('query_rule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_query_rule_concept_id'), ['concept_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_query_rule_phenotype_id'), ['phenotype_id'], unique=False)

    op.create_table('report_cohort_map',
    sa.Column('report_cohort_map_id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('dash_cohort_id', sa.Integer(), nullable=False),
    sa.Column('primary_cohort', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['dash_cohort_id'], ['dash_cohort.dash_cohort_id'], name=op.f('fk_report_cohort_map_dash_cohort_id_dash_cohort')),
    sa.ForeignKeyConstraint(['report_id'], ['report.report_id'], name=op.f('fk_report_cohort_map_report_id_report')),
    sa.PrimaryKeyConstraint('report_cohort_map_id', name=op.f('pk_report_cohort_map'))
    )
    op.create_table('dash_cohort_def',
    sa.Column('dash_cohort_def_id', sa.Integer(), nullable=False),
    sa.Column('dash_cohort_def_name', sa.String(length=250), nullable=False),
    sa.Column('dash_cohort_def_short_name', sa.String(length=50), nullable=False),
    sa.Column('measure_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['measure_id'], ['measure.measure_id'], name=op.f('fk_dash_cohort_def_measure_id_measure')),
    sa.PrimaryKeyConstraint('dash_cohort_def_id', name=op.f('pk_dash_cohort_def'))
    )
    op.create_table('indicator',
    sa.Column('indicator_id', sa.Integer(), nullable=False),
    sa.Column('indicator_description', sa.String(length=250), nullable=False),
    sa.Column('indicator_reference', sa.String(length=100), nullable=True),
    sa.Column('numerator_measure_id', sa.Integer(), nullable=False),
    sa.Column('denominator_measure_id', sa.Integer(), nullable=False),
    sa.Column('numerator_max_days_prior', sa.Integer(), nullable=True),
    sa.Column('numerator_max_days_post', sa.Integer(), nullable=True),
    sa.Column('denominator_max_days_prior', sa.Integer(), nullable=True),
    sa.Column('denominator_max_days_post', sa.Integer(), nullable=True),
    sa.Column('benchmark', sa.Integer(), nullable=True),
    sa.Column('benchmark_unit', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['denominator_measure_id'], ['measure.measure_id'], name=op.f('fk_indicator_denominator_measure_id_measure')),
    sa.ForeignKeyConstraint(['numerator_measure_id'], ['measure.measure_id'], name=op.f('fk_indicator_numerator_measure_id_measure')),
    sa.PrimaryKeyConstraint('indicator_id', name=op.f('pk_indicator'))
    )
    op.create_table('measure_relationship',
    sa.Column('parent_measure_id', sa.Integer(), nullable=False),
    sa.Column('child_measure_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['child_measure_id'], ['measure.measure_id'], name=op.f('fk_measure_relationship_child_measure_id_measure')),
    sa.ForeignKeyConstraint(['parent_measure_id'], ['measure.measure_id'], name=op.f('fk_measure_relationship_parent_measure_id_measure')),
    sa.PrimaryKeyConstraint('parent_measure_id', 'child_measure_id', name=op.f('pk_measure_relationship'))
    )
    op.create_table('measure_temporal_window',
    sa.Column('measure_id', sa.Integer(), nullable=False),
    sa.Column('candidate_measure_id', sa.Integer(), nullable=False),
    sa.Column('window_min_days', sa.Integer(), nullable=True),
    sa.Column('window_max_days', sa.Integer(), nullable=True),
    sa.Column('window_pick_strategy', sa.Enum('any', 'earliest', 'latest', 'closest', name='windowpickstrategy'), nullable=True),
    sa.Column('result_date_source', sa.Enum('anchor', 'candidate', 'greatest', 'least', name='resultdatesource'), nullable=True),
    sa.Column('require_same_resolver', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_measure_id'], ['measure.measure_id'], name=op.f('fk_measure_temporal_window_candidate_measure_id_measure')),
    sa.ForeignKeyConstraint(['measure_id'], ['measure.measure_id'], name=op.f('fk_measure_temporal_window_measure_id_measure')),
    sa.PrimaryKeyConstraint('measure_id', name=op.f('pk_measure_temporal_window'))
    )
    op.create_table('subquery_rule_map',
    sa.Column('subquery_id', sa.Integer(), nullable=False),
    sa.Column('query_rule_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['query_rule_id'], ['query_rule.query_rule_id'], name=op.f('fk_subquery_rule_map_query_rule_id_query_rule')),
    sa.ForeignKeyConstraint(['subquery_id'], ['subquery.subquery_id'], name=op.f('fk_subquery_rule_map_subquery_id_subquery')),
    sa.PrimaryKeyConstraint('subquery_id', 'query_rule_id', name=op.f('pk_subquery_rule_map'))
    )
    op.create_table('dash_cohort_def_map',
    sa.Column('dash_cohort_def_id', sa.Integer(), nullable=True),
    sa.Column('dash_cohort_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dash_cohort_def_id'], ['dash_cohort_def.dash_cohort_def_id'], name=op.f('fk_dash_cohort_def_map_dash_cohort_def_id_dash_cohort_def')),
    sa.ForeignKeyConstraint(['dash_cohort_id'], ['dash_cohort.dash_cohort_id'], name=op.f('fk_dash_cohort_def_map_dash_cohort_id_dash_cohort'))
    )
    op.create_table('report_indicator_map',
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('indicator_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicator.indicator_id'], name=op.f('fk_report_indicator_map_indicator_id_indicator')),
    sa.ForeignKeyConstraint(['report_id'], ['report.report_id'], name=op.f('fk_report_indicator_map_report_id_report')),
    sa.PrimaryKeyConstraint('report_id', 'indicator_id', name=op.f('pk_report_indicator_map'))
    )
    # ### end Alembic commands ###

    # The create_table calls above already declare these label sets, so on a
    # fresh database this is a no-op. It is here as the pattern to copy: any
    # revision that changes an enum calls sync_enum_labels with the full label
    # set, and the call is safe whether the type is being created here or
    # already exists with some of the labels.
    for enum_name, labels in _ENUM_LABELS.items():
        sync_enum_labels(enum_name, labels)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report_indicator_map')
    op.drop_table('dash_cohort_def_map')
    op.drop_table('subquery_rule_map')
    op.drop_table('measure_temporal_window')
    op.drop_table('measure_relationship')
    op.drop_table('indicator')
    op.drop_table('dash_cohort_def')
    op.drop_table('report_cohort_map')
    with op.batch_alter_table('query_rule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_query_rule_phenotype_id'))
        batch_op.drop_index(batch_op.f('ix_query_rule_concept_id'))

    op.drop_table('query_rule')
    op.drop_table('phenotype_definition')
    op.drop_table('measure')
    op.drop_table('subquery')
    op.drop_table('report')
    op.drop_table('phenotype')
    op.drop_table('dash_cohort')
    # ### end Alembic commands ###
